### ISSUE TITLE
Displaying The website with the help of Github Actions and Github Pages

### ISSUE THREAD

**Issue by vr62** [NJIT-WIS/project-2-team-rockedu#1]
*Set up Github Actions to display the website on URL*

### Tasks:
- [x] Research Github Actions and select an appropriate action to use
- [x] Configure the selected action to display the desired content
- [x] Test the action to ensure it works correctly
